module.exports = {
	fcSounds: '<svg width="452" height="257" xmlns="http://www.w3.org/2000/svg"><g><text font-weight="bold" font-style="italic" font-family="Helvetica, Arial, sans-serif" font-size="250" y="197" fill-opacity="0.05" fill="#000000">4sp</text></g></svg>',
	arrowClockwise: require('../node_modules/bootstrap-icons/icons/arrow-clockwise.svg').default,
	arrowsCollapse: require('../node_modules/bootstrap-icons/icons/arrows-collapse.svg').default,
	arrowsExpand: require('../node_modules/bootstrap-icons/icons/arrows-expand.svg').default,
	arrowRepeat: require('../node_modules/bootstrap-icons/icons/arrow-repeat.svg').default,
	chatRightQuote: require('../node_modules/bootstrap-icons/icons/chat-right-quote.svg').default,
	chevronDown: require('../node_modules/bootstrap-icons/icons/chevron-down.svg').default,
	close: require('../node_modules/bootstrap-icons/icons/plus.svg').default.replace('bi-plus', `bi-plus ${ns}-icon-close`).replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	gear: require('../node_modules/bootstrap-icons/icons/gear.svg').default,
	fileEarmarkImage: require('../node_modules/bootstrap-icons/icons/file-earmark-image.svg').default,
	fileEarmarkMusic: require('../node_modules/bootstrap-icons/icons/file-earmark-music.svg').default,
	filter: require('../node_modules/bootstrap-icons/icons/filter.svg').default,
	fullscreen: require('../node_modules/bootstrap-icons/icons/fullscreen.svg').default,
	fullscreenExit: require('../node_modules/bootstrap-icons/icons/fullscreen-exit.svg').default,
	image: require('../node_modules/bootstrap-icons/icons/image.svg').default,
	link: require('../node_modules/bootstrap-icons/icons/link-45deg.svg').default,
	musicNoteList: require('../node_modules/bootstrap-icons/icons/music-note-list.svg').default,
	play: require('../node_modules/bootstrap-icons/icons/play.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	playFill: require('../node_modules/bootstrap-icons/icons/play-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	pause: require('../node_modules/bootstrap-icons/icons/pause.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	pauseFill: require('../node_modules/bootstrap-icons/icons/pause-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	plus: require('../node_modules/bootstrap-icons/icons/plus-circle.svg').default,
	reboot: require('../node_modules/bootstrap-icons/icons/bootstrap-reboot.svg').default,
	search: require('../node_modules/bootstrap-icons/icons/search.svg').default,
	shuffle: require('../node_modules/bootstrap-icons/icons/shuffle.svg').default,
	skipEnd: require('../node_modules/bootstrap-icons/icons/skip-end.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	skipEndFill: require('../node_modules/bootstrap-icons/icons/skip-end-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	skipStart: require('../node_modules/bootstrap-icons/icons/skip-start.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	skipStartFill: require('../node_modules/bootstrap-icons/icons/skip-start-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="2 2 12 12"'),
	soundwave: require('../node_modules/bootstrap-icons/icons/soundwave.svg').default,
	tools: require('../node_modules/bootstrap-icons/icons/tools.svg').default,
	trash: require('../node_modules/bootstrap-icons/icons/trash.svg').default,
	volumeMute: require('../node_modules/bootstrap-icons/icons/volume-mute.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="1 1 14 14"'),
	volumeMuteFill: require('../node_modules/bootstrap-icons/icons/volume-mute-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="1 1 14 14"'),
	volumeUp: require('../node_modules/bootstrap-icons/icons/volume-up.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="1 1 14 14"'),
	volumeUpFill: require('../node_modules/bootstrap-icons/icons/volume-up-fill.svg').default.replace(/viewBox="[^"]+"/, 'viewBox="1 1 14 14"')
};
